/*
 * FILE : url_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PERL 5 */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#undef free
#undef malloc
#include <string.h>
#ifdef __cplusplus
}
#endif
/* Definitions for compiling Perl extensions on a variety of machines */

#if defined(WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerl *pPerl = (CPerl *) this;
#define MAGIC_CAST   (int (CPerl::*)(SV *, MAGIC *))
#define SWIGCLASS_STATIC 
#else
#define MAGIC_PPERL
#define MAGIC_CAST
#define SWIGCLASS_STATIC static
#endif


/*****************************************************************************
 * $Header: /home/beazley/SWIG/SWIG1.1b3/swig_lib/perl5/RCS/perl5ptr.swg,v 1.1 1996/12/26 22:17:29 beazley Exp beazley $
 *
 * perl5ptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is only used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer.
 *
 * char * SWIG_GetPtr(SV *obj, void **ptr, char *type)
 *
 *      Gets a pointer value from a Perl5 scalar value.  If there is a 
 *      type-mismatch, returns a character string to the received type.  
 *      On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *
 * $Log: perl5ptr.swg,v $
 * Revision 1.1  1996/12/26 22:17:29  beazley
 * Initial revision
 *
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

/* These are internal variables.   Should be static */

typedef struct SwigPtrType {
  char               *name;
  int                 len;
  void               *(*cast)(void *);
  struct SwigPtrType *next;
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */
static int SwigStart[256];             /* Table containing starting positions    */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

#ifndef PERL_OBJECT
SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
#else
SWIGSTATIC
#define SWIG_RegisterMapping(a,b,c) _SWIG_RegisterMapping(pPerl, a,b,c)
void _SWIG_RegisterMapping(CPerl *pPerl, char *origtype, char *newtype, void *(*cast)(void *)) {
#endif

  int i;
  SwigPtrType *t = 0, *t1;

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc(SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }
  while (t->next) {
    if (strcmp(t->name,newtype) == 0) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;
  t->next = t1;
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGSTATIC 
char *SWIG_GetPtr(SV *sv, void **ptr, char *_t)
#else
SWIGSTATIC
#define SWIG_GetPtr(a,b,c) _SWIG_GetPtr(pPerl,a,b,c)
char *_SWIG_GetPtr(CPerl *pPerl, SV *sv, void **ptr, char *_t)
#endif
{
  char temp_type[256];
  char *name,*_c;
  int  len,i,start,end;
  IV   tmp;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;

  /* If magical, apply more magic */

  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
	mg = mg_find(tsv,'P');
	if (mg) {
	  SV *rsv = mg->mg_obj;
	  if (sv_isobject(rsv)) {
	    tmp = SvIV((SV*)SvRV(rsv));
	  }
	}
      } else {
	return "Not a valid pointer value";
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    if (!_t) {
      *(ptr) = (void *) tmp;
      return (char *) 0;
    }
  } else if (sv == &sv_undef) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return (char *) 0;
  } else if (SvTYPE(sv) == SVt_RV) {       /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return (char *) 0;
    else
      return "Not a valid pointer value";
  } else {                                 /* Don't know what it is */
      *(ptr) = (void *) 0;
      return "Not a valid pointer value";
  }
  if (_t) {
    /* Now see if the types match */      

    if (!sv_isa(sv,_t)) {
      _c = HvNAME(SvSTASH(SvRV(sv)));
      if (!SwigPtrSort) {
	qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort);  
	for (i = 0; i < 256; i++) {
	  SwigStart[i] = SwigPtrN;
	}
	for (i = SwigPtrN-1; i >= 0; i--) {
	  SwigStart[SwigPtrTable[i].name[0]] = i;
	}
	for (i = 255; i >= 1; i--) {
	  if (SwigStart[i-1] > SwigStart[i])
	    SwigStart[i-1] = SwigStart[i];
	}
	SwigPtrSort = 1;
	for (i = 0; i < SWIG_CACHESIZE; i++)  
	  SwigCache[i].stat = 0;
      }
      /* First check cache for matches.  Uses last cache value as starting point */
      cache = &SwigCache[SwigLastCache];
      for (i = 0; i < SWIG_CACHESIZE; i++) {
	if (cache->stat) {
	  if (strcmp(_t,cache->name) == 0) {
	    if (strcmp(_c,cache->mapped) == 0) {
	      cache->stat++;
	      *ptr = (void *) tmp;
	      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
	      return (char *) 0;
	    }
	  }
	}
	SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	if (!SwigLastCache) cache = SwigCache;
	else cache++;
      }

      start = SwigStart[_t[0]];
      end = SwigStart[_t[0]+1];
      sp = &SwigPtrTable[start];
      while (start < end) {
	if (swigcmp(_t,sp) == 0) break;
	sp++;
	start++;
      }
      if (start >= end) sp = 0;
      if (sp) {
	while (swigcmp(_t,sp) == 0) {
	  name = sp->name;
	  len = sp->len;
	  tp = sp->next;
	  while(tp) {
	    if (tp->len >= 255) {
	      return _c;
	    }
	    strcpy(temp_type,tp->name);
	    strncat(temp_type,_t+len,255-tp->len);
	    if (sv_isa(sv,temp_type)) {
	      /* Get pointer value */
	      *ptr = (void *) tmp;
	      if (tp->cast) *ptr = (*(tp->cast))(*ptr);

	      strcpy(SwigCache[SwigCacheIndex].mapped,_c);
	      strcpy(SwigCache[SwigCacheIndex].name,_t);
	      SwigCache[SwigCacheIndex].stat = 1;
	      SwigCache[SwigCacheIndex].tp = tp;
	      SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	      return (char *) 0;
	    }
	    tp = tp->next;
	  } 
	  /* Hmmm. Didn't find it this time */
 	  sp++;
	}
      }
      /* Didn't find any sort of match for this data.  
	 Get the pointer value and return the received type */
      *ptr = (void *) tmp;
      return _c;
    } else {
      /* Found a match on the first try.  Return pointer value */
      *ptr = (void *) tmp;
      return (char *) 0;
    }
  } 
  *ptr = (void *) tmp;
  return (char *) 0;
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr
/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerl *pPerl, SV *sv, char *name, int (CPerl::*set)(SV *, MAGIC *), int (CPerl::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = get;
  mg->mg_virtual->svt_set = set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}

#define SWIG_init    boot_url

#define SWIG_name   "urlc::boot_url"
#define SWIG_varinit "urlc::var_url_init();"
#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
SWIGEXPORT(void,boot_url)(CV* cv);
#else
SWIGEXPORT(void,boot_url)(CPerl *, CV *cv);
#endif

#include "../url.h"
#ifndef PERL_OBJECT
#define swig_setiv(a,b) _swig_setiv(a,b)
static void _swig_setiv(char *name, long value) { 
#else
#define swig_setiv(a,b) _swig_setiv(pPerl,a,b)
static void _swig_setiv(CPerl *pPerl, char *name, long value) { 
#endif
     SV *sv; 
     sv = perl_get_sv(name,TRUE | 0x2);
     sv_setiv(sv, (IV) value);
     SvREADONLY_on(sv);
}

#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_url_var::
class _wrap_url_var : public CPerl {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

XS(_wrap_url_port) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_port(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_port. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_port(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_alloc) {

    url_t * _result;
    char * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_alloc(url,url_length);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _result = (url_t *)url_alloc(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"url_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_realloc) {

    int  _result;
    url_t * _arg0;
    char * _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: url_realloc(object,url,url_length);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_realloc. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _arg2 = (int )SvIV(ST(2));
    _result = (int )url_realloc(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_cannonicalize) {

    int  _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_cannonicalize(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_cannonicalize. Expected url_t.");
        XSRETURN(1);
    }
    _result = (int )url_cannonicalize(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_abs) {

    url_t * _result;
    url_t * _arg0;
    char * _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: url_abs(base,relative_string,relative_length);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_abs. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _arg2 = (int )SvIV(ST(2));
    _result = (url_t *)url_abs(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"url_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_abs_1) {

    url_t * _result;
    url_t * _arg0;
    url_t * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_abs_1(base,relative);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_abs_1. Expected url_t.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"url_t")) {
        croak("Type error in argument 2 of url_abs_1. Expected url_t.");
        XSRETURN(1);
    }
    _result = (url_t *)url_abs_1(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"url_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_netloc) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_netloc(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_netloc. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_netloc(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_auth) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_auth(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_auth. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_auth(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_all_path) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_all_path(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_all_path. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_all_path(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_copy) {

    url_t * _arg0;
    url_t * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_copy(to,from);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_copy. Expected url_t.");
        XSRETURN(1);
    }
    if (SWIG_GetPtr(ST(1),(void **) &_arg1,"url_t")) {
        croak("Type error in argument 2 of url_copy. Expected url_t.");
        XSRETURN(1);
    }
    url_copy(_arg0,_arg1);
    XSRETURN(argvi);
}

XS(_wrap_url_free) {

    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_free(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_free. Expected url_t.");
        XSRETURN(1);
    }
    url_free(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_url_parse) {

    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_parse(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_parse. Expected url_t.");
        XSRETURN(1);
    }
    url_parse(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_url_dump) {

    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_dump(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_dump. Expected url_t.");
        XSRETURN(1);
    }
    url_dump(_arg0);
    XSRETURN(argvi);
}

XS(_wrap_url_furl) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_furl(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_furl. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_furl(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_url) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_url(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_url. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_url(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_robots) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_robots(object);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_robots. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_robots(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url2object) {

    url_t * _result;
    char * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url2object(url,url_length);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _result = (url_t *)url2object(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setref_pv(ST(argvi++),"url_t", (void *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_furl_string) {

    char * _result;
    char * _arg0;
    int  _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: url_furl_string(url,url_length,flag);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _result = (char *)url_furl_string(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

XS(_wrap_url_cannonicalize_string) {

    char * _result;
    char * _arg0;
    int  _arg1;
    int  _arg2;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 3) || (items > 3)) 
        croak("Usage: url_cannonicalize_string(url,url_length,flag);");
    _arg0 = (char *) SvPV(ST(0),na);
    _arg1 = (int )SvIV(ST(1));
    _arg2 = (int )SvIV(ST(2));
    _result = (char *)url_cannonicalize_string(_arg0,_arg1,_arg2);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_info_set(_swigobj,_swigval) (_swigobj->info = _swigval,_swigval)
XS(_wrap_url_t_info_set) {

    int  _result;
    url_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_info_set(url_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_info_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )url_info_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define url_info_get(_swigobj) ((int ) _swigobj->info)
XS(_wrap_url_t_info_get) {

    int  _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_info_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_info_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (int )url_info_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * url_scheme_set(url_t *obj, char *val) {
    if (obj->scheme) free(obj->scheme);
    obj->scheme = (char *) malloc(strlen(val)+1);
    strcpy(obj->scheme,val);
    return val;
}
XS(_wrap_url_t_scheme_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_scheme_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_scheme_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_scheme_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_scheme_get(_swigobj) ((char *) _swigobj->scheme)
XS(_wrap_url_t_scheme_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_scheme_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_scheme_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_scheme_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_host_set(url_t *obj, char *val) {
    if (obj->host) free(obj->host);
    obj->host = (char *) malloc(strlen(val)+1);
    strcpy(obj->host,val);
    return val;
}
XS(_wrap_url_t_host_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_host_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_host_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_host_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_host_get(_swigobj) ((char *) _swigobj->host)
XS(_wrap_url_t_host_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_host_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_host_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_host_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_port_set(url_t *obj, char *val) {
    if (obj->port) free(obj->port);
    obj->port = (char *) malloc(strlen(val)+1);
    strcpy(obj->port,val);
    return val;
}
XS(_wrap_url_t_port_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_port_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_port_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_port_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_port_get(_swigobj) ((char *) _swigobj->port)
XS(_wrap_url_t_port_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_port_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_port_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_port_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_path_set(url_t *obj, char *val) {
    if (obj->path) free(obj->path);
    obj->path = (char *) malloc(strlen(val)+1);
    strcpy(obj->path,val);
    return val;
}
XS(_wrap_url_t_path_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_path_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_path_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_path_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_path_get(_swigobj) ((char *) _swigobj->path)
XS(_wrap_url_t_path_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_path_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_path_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_path_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_params_set(url_t *obj, char *val) {
    if (obj->params) free(obj->params);
    obj->params = (char *) malloc(strlen(val)+1);
    strcpy(obj->params,val);
    return val;
}
XS(_wrap_url_t_params_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_params_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_params_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_params_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_params_get(_swigobj) ((char *) _swigobj->params)
XS(_wrap_url_t_params_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_params_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_params_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_params_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_query_set(url_t *obj, char *val) {
    if (obj->query) free(obj->query);
    obj->query = (char *) malloc(strlen(val)+1);
    strcpy(obj->query,val);
    return val;
}
XS(_wrap_url_t_query_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_query_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_query_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_query_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_query_get(_swigobj) ((char *) _swigobj->query)
XS(_wrap_url_t_query_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_query_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_query_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_query_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_frag_set(url_t *obj, char *val) {
    if (obj->frag) free(obj->frag);
    obj->frag = (char *) malloc(strlen(val)+1);
    strcpy(obj->frag,val);
    return val;
}
XS(_wrap_url_t_frag_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_frag_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_frag_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_frag_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_frag_get(_swigobj) ((char *) _swigobj->frag)
XS(_wrap_url_t_frag_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_frag_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_frag_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_frag_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_user_set(url_t *obj, char *val) {
    if (obj->user) free(obj->user);
    obj->user = (char *) malloc(strlen(val)+1);
    strcpy(obj->user,val);
    return val;
}
XS(_wrap_url_t_user_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_user_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_user_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_user_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_user_get(_swigobj) ((char *) _swigobj->user)
XS(_wrap_url_t_user_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_user_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_user_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_user_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_passwd_set(url_t *obj, char *val) {
    if (obj->passwd) free(obj->passwd);
    obj->passwd = (char *) malloc(strlen(val)+1);
    strcpy(obj->passwd,val);
    return val;
}
XS(_wrap_url_t_passwd_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_passwd_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_passwd_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_passwd_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_passwd_get(_swigobj) ((char *) _swigobj->passwd)
XS(_wrap_url_t_passwd_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_passwd_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_passwd_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_passwd_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

static char * url_pool_set(url_t *obj, char *val) {
    if (obj->pool) free(obj->pool);
    obj->pool = (char *) malloc(strlen(val)+1);
    strcpy(obj->pool,val);
    return val;
}
XS(_wrap_url_t_pool_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_pool_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_pool_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_pool_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_pool_get(_swigobj) ((char *) _swigobj->pool)
XS(_wrap_url_t_pool_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_pool_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_pool_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_pool_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_pool_size_set(_swigobj,_swigval) (_swigobj->pool_size = _swigval,_swigval)
XS(_wrap_url_t_pool_size_set) {

    int  _result;
    url_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_pool_size_set(url_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_pool_size_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )url_pool_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define url_pool_size_get(_swigobj) ((int ) _swigobj->pool_size)
XS(_wrap_url_t_pool_size_get) {

    int  _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_pool_size_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_pool_size_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (int )url_pool_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * url_furl_set(url_t *obj, char *val) {
    if (obj->furl) free(obj->furl);
    obj->furl = (char *) malloc(strlen(val)+1);
    strcpy(obj->furl,val);
    return val;
}
XS(_wrap_url_t_furl_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_furl_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_furl_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_furl_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_furl_get(_swigobj) ((char *) _swigobj->furl)
XS(_wrap_url_t_furl_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_furl_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_furl_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_furl_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_furl_size_set(_swigobj,_swigval) (_swigobj->furl_size = _swigval,_swigval)
XS(_wrap_url_t_furl_size_set) {

    int  _result;
    url_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_furl_size_set(url_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_furl_size_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )url_furl_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define url_furl_size_get(_swigobj) ((int ) _swigobj->furl_size)
XS(_wrap_url_t_furl_size_get) {

    int  _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_furl_size_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_furl_size_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (int )url_furl_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * url_url_set(url_t *obj, char *val) {
    if (obj->url) free(obj->url);
    obj->url = (char *) malloc(strlen(val)+1);
    strcpy(obj->url,val);
    return val;
}
XS(_wrap_url_t_url_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_url_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_url_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_url_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_url_get(_swigobj) ((char *) _swigobj->url)
XS(_wrap_url_t_url_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_url_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_url_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_url_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_url_size_set(_swigobj,_swigval) (_swigobj->url_size = _swigval,_swigval)
XS(_wrap_url_t_url_size_set) {

    int  _result;
    url_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_url_size_set(url_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_url_size_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )url_url_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define url_url_size_get(_swigobj) ((int ) _swigobj->url_size)
XS(_wrap_url_t_url_size_get) {

    int  _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_url_size_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_url_size_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (int )url_url_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

static char * url_robots_set(url_t *obj, char *val) {
    if (obj->robots) free(obj->robots);
    obj->robots = (char *) malloc(strlen(val)+1);
    strcpy(obj->robots,val);
    return val;
}
XS(_wrap_url_t_robots_set) {

    char * _result;
    url_t * _arg0;
    char * _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_robots_set(url_t *,char *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_robots_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (char *) SvPV(ST(1),na);
    _result = (char *)url_robots_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_robots_get(_swigobj) ((char *) _swigobj->robots)
XS(_wrap_url_t_robots_get) {

    char * _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_robots_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_robots_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (char *)url_robots_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) _result);
    XSRETURN(argvi);
}

#define url_robots_size_set(_swigobj,_swigval) (_swigobj->robots_size = _swigval,_swigval)
XS(_wrap_url_t_robots_size_set) {

    int  _result;
    url_t * _arg0;
    int  _arg1;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 2) || (items > 2)) 
        croak("Usage: url_t_robots_size_set(url_t *,int );");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_robots_size_set. Expected url_t.");
        XSRETURN(1);
    }
    _arg1 = (int )SvIV(ST(1));
    _result = (int )url_robots_size_set(_arg0,_arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

#define url_robots_size_get(_swigobj) ((int ) _swigobj->robots_size)
XS(_wrap_url_t_robots_size_get) {

    int  _result;
    url_t * _arg0;
    int argvi = 0;
    dXSARGS ;

    cv = cv;
    if ((items < 1) || (items > 1)) 
        croak("Usage: url_t_robots_size_get(url_t *);");
    if (SWIG_GetPtr(ST(0),(void **) &_arg0,"url_t")) {
        croak("Type error in argument 1 of url_t_robots_size_get. Expected url_t.");
        XSRETURN(1);
    }
    _result = (int )url_robots_size_get(_arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) _result);
    XSRETURN(argvi);
}

XS(_wrap_perl5_url_var_init) {
    dXSARGS;
    SV *sv;
    cv = cv; items = items;
    swig_setiv("URL_INFO_CANNONICAL", (long) 0x0001);
    swig_setiv("URL_INFO_URL", (long) 0x0002);
    swig_setiv("URL_INFO_FURL", (long) 0x0004);
    swig_setiv("URL_INFO_RELATIVE", (long) 0x0008);
    swig_setiv("URL_INFO_RELATIVE_PATH", (long) 0x0010);
    swig_setiv("URL_INFO_EMPTY", (long) 0x0020);
    swig_setiv("URL_INFO_HTTP", (long) 0x0040);
    swig_setiv("URL_INFO_FTP", (long) 0x0080);
    swig_setiv("URL_INFO_NEWS", (long) 0x0100);
    swig_setiv("URL_INFO_FILE", (long) 0x0200);
    swig_setiv("URL_INFO_ROBOTS", (long) 0x0400);
    swig_setiv("URL_INFO_SCHEME_MASK", (long) 0x03c0);
    swig_setiv("URL_NOT_CANNONICAL", (long) -1);
    swig_setiv("URL_CANNONICAL", (long) 0);
    swig_setiv("URL_FURL_REAL_PATH", (long) 1);
    swig_setiv("URL_FURL_NOP", (long) 0);
    swig_setiv("URL_STRING_FURL_STYLE", (long) 0x01);
    swig_setiv("URL_STRING_URL_STYLE", (long) 0x02);
    swig_setiv("URL_STRING_ROBOTS_STYLE", (long) 0x04);
    swig_setiv("URL_STRING_URL_NOHASH_STYLE", (long) 0x08);
    XSRETURN(1);
}
#ifdef __cplusplus
extern "C"
#endif
XS(boot_url) {
	 dXSARGS;
	 char *file = __FILE__;
	 cv = cv; items = items;
	 newXS("urlc::var_url_init", _wrap_perl5_url_var_init, file);
	 newXS("urlc::url_port", _wrap_url_port, file);
	 newXS("urlc::url_alloc", _wrap_url_alloc, file);
	 newXS("urlc::url_realloc", _wrap_url_realloc, file);
	 newXS("urlc::url_cannonicalize", _wrap_url_cannonicalize, file);
	 newXS("urlc::url_abs", _wrap_url_abs, file);
	 newXS("urlc::url_abs_1", _wrap_url_abs_1, file);
	 newXS("urlc::url_netloc", _wrap_url_netloc, file);
	 newXS("urlc::url_auth", _wrap_url_auth, file);
	 newXS("urlc::url_all_path", _wrap_url_all_path, file);
	 newXS("urlc::url_copy", _wrap_url_copy, file);
	 newXS("urlc::url_free", _wrap_url_free, file);
	 newXS("urlc::url_parse", _wrap_url_parse, file);
	 newXS("urlc::url_dump", _wrap_url_dump, file);
	 newXS("urlc::url_furl", _wrap_url_furl, file);
	 newXS("urlc::url_url", _wrap_url_url, file);
	 newXS("urlc::url_robots", _wrap_url_robots, file);
	 newXS("urlc::url2object", _wrap_url2object, file);
	 newXS("urlc::url_furl_string", _wrap_url_furl_string, file);
	 newXS("urlc::url_cannonicalize_string", _wrap_url_cannonicalize_string, file);
	 newXS("urlc::url_t_info_set", _wrap_url_t_info_set, file);
	 newXS("urlc::url_t_info_get", _wrap_url_t_info_get, file);
	 newXS("urlc::url_t_scheme_set", _wrap_url_t_scheme_set, file);
	 newXS("urlc::url_t_scheme_get", _wrap_url_t_scheme_get, file);
	 newXS("urlc::url_t_host_set", _wrap_url_t_host_set, file);
	 newXS("urlc::url_t_host_get", _wrap_url_t_host_get, file);
	 newXS("urlc::url_t_port_set", _wrap_url_t_port_set, file);
	 newXS("urlc::url_t_port_get", _wrap_url_t_port_get, file);
	 newXS("urlc::url_t_path_set", _wrap_url_t_path_set, file);
	 newXS("urlc::url_t_path_get", _wrap_url_t_path_get, file);
	 newXS("urlc::url_t_params_set", _wrap_url_t_params_set, file);
	 newXS("urlc::url_t_params_get", _wrap_url_t_params_get, file);
	 newXS("urlc::url_t_query_set", _wrap_url_t_query_set, file);
	 newXS("urlc::url_t_query_get", _wrap_url_t_query_get, file);
	 newXS("urlc::url_t_frag_set", _wrap_url_t_frag_set, file);
	 newXS("urlc::url_t_frag_get", _wrap_url_t_frag_get, file);
	 newXS("urlc::url_t_user_set", _wrap_url_t_user_set, file);
	 newXS("urlc::url_t_user_get", _wrap_url_t_user_get, file);
	 newXS("urlc::url_t_passwd_set", _wrap_url_t_passwd_set, file);
	 newXS("urlc::url_t_passwd_get", _wrap_url_t_passwd_get, file);
	 newXS("urlc::url_t_pool_set", _wrap_url_t_pool_set, file);
	 newXS("urlc::url_t_pool_get", _wrap_url_t_pool_get, file);
	 newXS("urlc::url_t_pool_size_set", _wrap_url_t_pool_size_set, file);
	 newXS("urlc::url_t_pool_size_get", _wrap_url_t_pool_size_get, file);
	 newXS("urlc::url_t_furl_set", _wrap_url_t_furl_set, file);
	 newXS("urlc::url_t_furl_get", _wrap_url_t_furl_get, file);
	 newXS("urlc::url_t_furl_size_set", _wrap_url_t_furl_size_set, file);
	 newXS("urlc::url_t_furl_size_get", _wrap_url_t_furl_size_get, file);
	 newXS("urlc::url_t_url_set", _wrap_url_t_url_set, file);
	 newXS("urlc::url_t_url_get", _wrap_url_t_url_get, file);
	 newXS("urlc::url_t_url_size_set", _wrap_url_t_url_size_set, file);
	 newXS("urlc::url_t_url_size_get", _wrap_url_t_url_size_get, file);
	 newXS("urlc::url_t_robots_set", _wrap_url_t_robots_set, file);
	 newXS("urlc::url_t_robots_get", _wrap_url_t_robots_get, file);
	 newXS("urlc::url_t_robots_size_set", _wrap_url_t_robots_size_set, file);
	 newXS("urlc::url_t_robots_size_get", _wrap_url_t_robots_size_get, file);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("unsigned short","short",0);
	 SWIG_RegisterMapping("url","url_t",0);
	 SWIG_RegisterMapping("url","struct url",0);
	 SWIG_RegisterMapping("long","unsigned long",0);
	 SWIG_RegisterMapping("long","signed long",0);
	 SWIG_RegisterMapping("signed short","short",0);
	 SWIG_RegisterMapping("signed int","int",0);
	 SWIG_RegisterMapping("short","unsigned short",0);
	 SWIG_RegisterMapping("short","signed short",0);
	 SWIG_RegisterMapping("unsigned long","long",0);
	 SWIG_RegisterMapping("int","unsigned int",0);
	 SWIG_RegisterMapping("int","signed int",0);
	 SWIG_RegisterMapping("url_t","struct url",0);
	 SWIG_RegisterMapping("url_t","url",0);
	 SWIG_RegisterMapping("unsigned int","int",0);
	 SWIG_RegisterMapping("struct url","url_t",0);
	 SWIG_RegisterMapping("struct url","url",0);
	 SWIG_RegisterMapping("signed long","long",0);
	 ST(0) = &sv_yes;
	 XSRETURN(1);
}
